[[redirects]]
  from = "/api/*"
  to = "https://front-end-task-dot-result-analytics-dot-fpls-dev.uc.r.appspot.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200